### PR TITLE
add badges in readme.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Travis-ci
* https://travis-ci.org/sindresorhus/github-notifier-chrome

npm dependencies
* https://david-dm.org/sindresorhus/github-notifier-chrome#info=devDependencies

### CODE REVIEW

**Comment by kevva** [comment]
Travis, yes. npm, no.

**Comment by PeterDaveHello** [comment]
Updated.

**Comment by PeterDaveHello** [comment]
May I know the reason why you don't like the npm dependencies badge?

**Comment by kevva** [comment]
@sindresorhus doesn't use it in any of his repos.

**Comment by PeterDaveHello** [comment]
May we can give it a try, it's useful, especially when the dependency is in insecure status.

**Comment by gcochard** [comment]
The dependencies for this project are all devDependencies, so there's no *real* need for the badge. Thanks for the PR!

**Pull request merged**
