### PR TITLE
upgrade devDependencies - eslint to 1.0.0

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by kevva** [comment]
Tests are failing, could you fix that?

**Comment by PeterDaveHello** [comment]
hmmmm ... it passed the test locally

```
> @ test /run/shm/github-notifier-chrome
> mocha



  basic functionality
    ✓ should register alarm callback
    ✓ should call gitHubNotifCount on chrome alarm fired


  2 passing (10ms)
```

**Comment by kevva** [comment]
Run `npm test`.

**Comment by PeterDaveHello** [comment]
Yes, that's the result of `npm test` ... I know `npm test`.

**Comment by kevva** [comment]
Should be good now. Thanks :).

**Comment by PeterDaveHello** [comment]
Oops, you are so fast on fixing it, I'm still looking at it, thanks @kevva

**Pull request closed without merging**
